#include<iostream>
using namespace std;

int main(){
	/*Caza de errores
	El bloque try-catch permite deciri que hacer
	en caso de presentarse una excepcion controlada
	o sea aquella que se envia por medio de throw.*/
	
	return 111;
}
